
#priority 9999
import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDictEntry;

global odItemMap as IItemStack[string] = {

  dustIron: <thermalfoundation:material:0>,
  dustGold: <thermalfoundation:material:1>,
  dustCopper: <thermalfoundation:material:64>,
  dustTin: <thermalfoundation:material:65>,
  dustSilver: <thermalfoundation:material:66>,
  dustLead: <thermalfoundation:material:67>,

  ingotIron : <minecraft:iron_ingot>,
  ingotGold : <minecraft:gold_ingot>,
  ingotCopper : <thermalfoundation:material:128>,
  ingotTin : <thermalfoundation:material:129>,
  ingotSilver : <thermalfoundation:material:130>,
  ingotLead : <thermalfoundation:material:131>,
  ingotAluminum : <thermalfoundation:material:132>,
  ingotNickel : <thermalfoundation:material:133>,
  ingotPlatinum : <thermalfoundation:material:134>,
  ingotIridium : <thermalfoundation:material:135>,
  ingotSteel : <thermalfoundation:material:160>,
  ingotElectrum : <thermalfoundation:material:161>,
  ingotInvar : <thermalfoundation:material:162>,
  ingotBronze : <thermalfoundation:material:163>,
  ingotConstantan : <thermalfoundation:material:164>,
  ingotSignalum : <thermalfoundation:material:165>,
  ingotLumium : <thermalfoundation:material:166>,
  ingotEnderium : <thermalfoundation:material:167>,
  ingotRefinedIron : <techreborn:ingot:19>,

  plateWood : <techreborn:plates:3>,
  plateStone : getCTItemByODName("plateStone"),
  plateQuartz : <moreplates:nether_quartz_plate>,
  plateIron : <thermalfoundation:material:32>,
  plateGold : <thermalfoundation:material:33>,
  plateCopper : <thermalfoundation:material:320>,
  plateTin : <thermalfoundation:material:321>,
  plateSilver : <thermalfoundation:material:322>,
  plateLead : <thermalfoundation:material:323>,
  plateAluminum : <thermalfoundation:material:324>,
  plateNickel : <thermalfoundation:material:325>,
  platePlatinum : <thermalfoundation:material:326>,
  plateIridium : <thermalfoundation:material:327>,
  plateSteel : <thermalfoundation:material:352>,
  plateElectrum : <thermalfoundation:material:353>,
  plateInvar : <thermalfoundation:material:354>,
  plateBronze : <thermalfoundation:material:355>,
  plateConstantan : <thermalfoundation:material:356>,
  plateSignalum : <thermalfoundation:material:357>,
  plateLumium : <thermalfoundation:material:358>,
  plateEnderium : <thermalfoundation:material:359>,
  plateRefinedIron : <techreborn:plates:35>,

  boltWood : getCTItemByODName("boltWood"),
  boltStone : getCTItemByODName("boltStone"),
  boltIron : getCTItemByODName("boltIron"),
  boltGold : getCTItemByODName("boltGold"),
  boltCopper : getCTItemByODName("boltCopper"),
  boltTin : getCTItemByODName("boltTin"),
  boltSilver : getCTItemByODName("boltSilver"),
  boltLead : getCTItemByODName("boltLead"),
  boltAluminum : getCTItemByODName("boltAluminum"),
  boltNickel : getCTItemByODName("boltNickel"),
  boltPlatinum : getCTItemByODName("boltPlatinum"),
  boltIridium : getCTItemByODName("boltIridium"),
  boltSteel : getCTItemByODName("boltSteel"),
  boltElectrum : getCTItemByODName("boltElectrum"),
  boltInvar : getCTItemByODName("boltInvar"),
  boltBronze : getCTItemByODName("boltBronze"),
  boltConstantan : getCTItemByODName("boltConstantan"),
  boltSignalum : getCTItemByODName("boltSignalum"),
  boltLumium : getCTItemByODName("boltLumium"),
  boltEnderium : getCTItemByODName("boltEnderium"),

  stickWood : <minecraft:stick>,
  stickStone : <exnihilocreatio:item_material:6>,
  stickIron: <immersiveengineering:material:1>,
  stickGold : <moreplates:gold_stick>,
  stickCopper : <moreplates:copper_stick>,
  stickTin : <moreplates:tin_stick>,
  stickSilver : <moreplates:silver_stick>,
  stickLead : <moreplates:lead_stick>,
  stickAluminum : <immersiveengineering:material:3>,
  stickNickel : <moreplates:nickel_stick>,
  stickPlatinum : <moreplates:platinum_stick>,
  stickIridium : <moreplates:iridium_stick>,
  stickSteel : <immersiveengineering:material:2>,
  stickElectrum : <moreplates:electrum_stick>,
  stickInvar : <moreplates:invar_stick>,
  stickBronze : <moreplates:bronze_stick>,
  stickConstantan : <moreplates:constantan_stick>,
  stickSignalum : <moreplates:signalum_stick>,
  stickLumium : <moreplates:lumium_stick>,
  stickEnderium : <moreplates:enderium_stick>,

  gearWood : <thermalfoundation:material:22>,
  gearStone : <thermalfoundation:material:23>,
  gearIron : <thermalfoundation:material:24>,
  gearGold : <thermalfoundation:material:25>,
  gearCopper : <thermalfoundation:material:256>,
  gearTin : <thermalfoundation:material:257>,
  gearSilver : <thermalfoundation:material:258>,
  gearLead : <thermalfoundation:material:259>,
  gearAluminum : <thermalfoundation:material:260>,
  gearNickel : <thermalfoundation:material:261>,
  gearPlatinum : <thermalfoundation:material:262>,
  gearIridium : <thermalfoundation:material:263>,
  gearSteel : <thermalfoundation:material:288>,
  gearElectrum : <thermalfoundation:material:289>,
  gearInvar : <thermalfoundation:material:290>,
  gearBronze : <thermalfoundation:material:291>,
  gearConstantan : <thermalfoundation:material:292>,
  gearSignalum : <thermalfoundation:material:293>,
  gearLumium : <thermalfoundation:material:294>,
  gearEnderium : <thermalfoundation:material:295>,
  gearDiamond : <thermalfoundation:material:26>,
  gearEmerald : <thermalfoundation:material:27>,
  gearQuartz : <moreplates:nether_quartz_gear>
} as IItemStack[string];

var joapcaOreName = [
  "Aluminium",
  "Ardite",
  "Boron",
  "Cobalt",
  "Copper",
  "Draconium",
  "Gold",
  "Iridium",
  "Iron",
  "Lead",
  "Lithium",
  "Magnesium",
  "Mithril",
  "Nickel",
  "Osmium",
  "Platinum",
  "Silver",
  "Thorium",
  "Tin",
  "Tungsten",
  "Uranium"
] as string[];

for i in joapcaOreName {
  odItemMap['piece' + i] = getJAOPCAItemByODName("piece" + i);
  odItemMap['ore' + i] = getJAOPCAItemByODName("ore" + i);
}
